apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - workload/cluster.yaml
  - workload/scheduled-backup.yaml

generators:
  - secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: kustomize
