# UniFi Controller credentials
# This file should be encrypted with SOPS before committing
#
# To encrypt:
#   sops -e -i k8s/apps/unpoller/config/secret.yaml
#
# Create API key in UniFi OS: Settings > System > Advanced > API
apiVersion: v1
kind: Secret
metadata:
    name: unpoller-credentials
    namespace: unpoller
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5PdZLKalQJ4T+OjF4yRtZA/BoZ/qRIEJCn+ULbxlVF0jS/F9Kyl6MO/M90pvsyHfhgkwp23mi2gD7mQ=,iv:u8n3Rvf8xRpfWl6FonIHf726P6v3skZ2sSqv22TROBA=,tag:psWWVntNqEcTjlAqYBijfA==,type:comment]
    UNIFI_URL: ENC[AES256_GCM,data:5nNF6yl3d46zTJ3x95+1nx3fxg==,iv:2ldCSiJ3jq7spc6SdeiUDJjeGDwzejegOPNsvrIfFrE=,tag:Jtiu82hCEfz7/sNnoe7aGQ==,type:str]
    #ENC[AES256_GCM,data:KvoGdB566wGSxxevo332Aw433+5S/w==,iv:a4yEzaPrt+9feTQbhkieKMuM9m4I1heAf0+JtNcdUcM=,tag:Y76g2FgyyT1jWP9Y0OApyg==,type:comment]
    UNIFI_API_KEY: ENC[AES256_GCM,data:Q2PW6h8mhrB2sQq6i+m/Y7R8V/6BMLLb2Bd4kceFBK4=,iv:o32XMmR+XGgCoBi3gg6+KWm0Izzn3SMlJ7a1nkePMFM=,tag:Q4eK/t/Sa5kT9zjB+5+XXQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcnNYWVBwdjh2U3REN1Er
            WjJSSC81Ri81c043RzViYyt1c3BrWm81Z1N3CjNTVUpHWGtBVjV6U3JZcVVkeWNP
            TjhQSVR0czNvVW1MbUJWWW05byswTjgKLS0tIGZ3ci9ZWCtod0o1aWtaMGhlNU9W
            VEdRb0crcUwzdGZwZDNDK3pTTG9POFUK20YVtHfVJp3QaR4jwuK3Se+i94EDwVZb
            QU/6lQ474Vbr7YKmzYN0xt6MToOYjl93Hs39i8AQrTuSIUqjthOIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:26:42Z"
    mac: ENC[AES256_GCM,data:62ic259b96zgdwdXS2T7ctUH6Ca22EFw/PKp7OWT18rtJp93LKD0grmSRggUJnrO30Uy68MIvZxSPz7+nqphf6/na+4SGVUMiGJbKAwFCnVbMVysvQXU31lLIT40CAeNnUq84RuB44ZbQ2JFrXozuTTXsZWkh4xIiNwi9FGY250=,iv:dkOOWAEHJgn8t4ZHY5aJdMhdJJs0E6bi1tFG38uMogc=,tag:x1xrurjoWACXQy2qS/lVtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
