apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mqtt

resources:
  - namespace.yaml
  - config/configmap.yaml
  - workload/statefulset.yaml
  - networking/services.yaml
  - networking/ingress.yaml

generators:
  - config/secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: mqtt
