apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: keycloak
    labels:
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/component: config
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BEkLfvYTnim+rDo1wXw205Kr7CXZIxC9kFjZT7HYiKVtdwSHxeqG8lVBlw==,iv:+u8/5Qc3CAN0yiBzC44/vi8ALYMCDwOLmyjdM4JAGPE=,tag:Ao39nFVS/cpc3MSDcOri+Q==,type:comment]
    #ENC[AES256_GCM,data:yjZ9BTi9b0bRRv6op18byE9RVuGKvBnR3HI9/M376nnd478=,iv:2KHr7sZcDzNfTDq15y8KsE4tbfASmbREr1dwu+Ucb1w=,tag:mHDxP0DLiJdPaD9i6DJL9A==,type:comment]
    #ENC[AES256_GCM,data:Cc8/itZkLYKICKL01mHY+ss9qbBEMByK/OJI,iv:552NX7xPfJyF0bOwZkMljfZfDJ1H9gGX55nSCzO9ImA=,tag:p4aNh7U/nrZfBTG17kESeQ==,type:comment]
    #ENC[AES256_GCM,data:drs9hatIMYw6GCU1DN5/bMEnHUhNS6UTzUKySqw=,iv:DIaMY+xu1lRIOHlSJZ+KcMtI678CGc5w8t1Mrw2Az30=,tag:rkknFjWn969cL7gYnEBNLQ==,type:comment]
    #ENC[AES256_GCM,data:YfH4Unzje6sBrFDgkk05Z7x4OhepcEvZc66FD8DVnBi1K0xPYUqF3rJTReZdaWO1/567v/joGVzGaUoT+Op1DA==,iv:P4rh6lhB2Z5i5DrCFr2LWWgEF9OzW+i9ISNqclsG5bM=,tag:UdgQh6OpjjdJMpruXJNNMA==,type:comment]
    #ENC[AES256_GCM,data:CAWD13ZxIwcO7guCT1VQ11qnMh11YF9f5eACovUlsBowMqpztQ777Ov4pXZKAf4=,iv:JT+n//WiZFs5DQaiPjqcTIYrGbh1xsmTlfE/Lu7ewBc=,tag:y14Tnl4Z1XxZK5TzNgYeOg==,type:comment]
    client-id: ENC[AES256_GCM,data:OI1EbQYkFjaBQnbr,iv:YFC7oYOfOL1oKw785jqx9vlU82yRxuEmEs6GCFIcTC0=,tag:xZKJ3Nj4OtZJ3c7tMM1MyQ==,type:str]
    client-secret: ENC[AES256_GCM,data:1VcRd10v04o/5EWwi2bp9yUWuM5Rm0TBQINe12wetwc=,iv:Lm6qKM7IWt6h9hiClMEv78Haxe2KlrKe1l23gvMh+jU=,tag:GvnQ0wv4GojGb5UT0fsK7A==,type:str]
    #ENC[AES256_GCM,data:tVLNcXrleU95LMEVzOh4Znr7cflZ77KsyqrXupfXWlUccA9QFLH1GCGH7CXbXwyDmpwm4Kyq1zjm,iv:RP9vYK2gBZUtUXm7bvGKJa2IlznmbvdNjHdi/SRwjgU=,tag:nSYAFq31Rfc/nuTjiunsxA==,type:comment]
    cookie-secret: ENC[AES256_GCM,data:hgXkTh0eVmcYCBnm9R1sGp/+Xu7FXD0C16m1LUsZB1HGJ9SHZwMvO8nOCuI=,iv:U21od0XJbR7JKgy7SmgotKPp5lujXRa4V7p4KB6GVlw=,tag:KwNKEtrlReanK9iuYmzC6Q==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcjYzZmkrNnh3dnlZTi9i
            dVVRVytjdGVCTUdiVmpwWnYra0NIYmw1bkdBCmRUV0FjTlk4UmViUGhPNm9IcnZP
            NGthYW5OVy9jQnlWeU1IdHQwWTkzTGsKLS0tIHRzc1NnYUQ3YjZsZHpCQTBUR1pv
            UUdvODNQZXo2VWFOTWNxNGE1c0h1cFkK2dYKNiGPouviJCmz4YZiNQB7lziiGdPC
            7XyBu9N/rGhPP0mKQgDGVTcILn+78GV1pXrib2wYLLQeTmYDzA86bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:47:35Z"
    mac: ENC[AES256_GCM,data:lS/2pDGs5WJ0YVN0+hHdDYXYSRugWVi2VJOGcVj03R+2cvz2yH61kNmWfjLfdr6EXWbvVziskRss+nCKiSwBh5V5HfQbfs1Zll/c/GZy49xiraTnzRmmatHZ7gZLNtzGokkeodYR+QIyQGDMN8Q+dyKdg2H/wVhgkjF+EAT0hwE=,iv:wu9EBp+rcj6K73aO0VgTIGJrjur+jnqx1gsHdxoXFr0=,tag:HiqYD0gEeOkaWbFn4nP1aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
