apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: config
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OGKZ+BJ42sw13qAcE8ku1FW3TcNW9ib3cD7yaL22Acbkq5SJWbQ=,iv:q2dTW6c++zHXsWP6RpoyYOiEz6we+kwLnRnmL97rbKk=,tag:OWxFVehK8f1cfd/Yaxd/Tg==,type:comment]
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:HCFHz3c=,iv:phgOdAthjWG4OSBZpTMs45F7FZm6QCpojiMNj+C1YAE=,tag:t3aP82T3xP6MOc7PWrsZIQ==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:aJNaHN+k/QYAzg==,iv:ZOy5tcyvZgjjiQT5/pP5Nab4FjIHhWkyMrCnRXE7/LA=,tag:JChzgesAW2lVz+pB6S9o9Q==,type:str]
    #ENC[AES256_GCM,data:XC2h0krrlU0sPJWg+tahkC2tdBr25QPLRUpPs7iaWyhgZQj0TEffIDkJOdkswnZwqcQGOLq8mY0=,iv:ZY+mMiwDMCzwY4PT/nlsdX/PD3h1bsDv+rXIL7rPnNk=,tag:k1fxcKInE/9CpZyMtfd55A==,type:comment]
    KC_DB_URL: ENC[AES256_GCM,data:gpg5+kWwLZQCgsn09sBRsdY/9vIJeEVKtGolB8MpsNJhzrvmD2gYk8hP3wf4I82envmmo5Ux6J6NTLB2,iv:k76eHAGWsSPA+YaW5/SBcWcQuaFMTFWHYNdI0UW+aQA=,tag:05g13lMD0oBfwWtpUDdGOA==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:AGPY,iv:k+l0eiKd4Wy3ENiaa1hr6Q3eOX/xDOTU+6ZYxakcUrY=,tag:BHU9FJ7PAVFw7ep7Ct4+Tw==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:QCHiEbl/88UKE5vstwAc1X1YLTSIJAZcuYIuyAqmmf93yQwxwPsBEmHLOag1cJ1OwXtYAlppd/3lkSfT/qdyKQ==,iv:e4c/TYX0Oi9gGurBYpPiSk04eZuSS+qWfVRKh5r9Kzc=,tag:j8am9iTWrBdMhJsTmmSt3g==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTHdsQkVFR2R3ZkFkcGZ2
            bjdXZ1dtQXIza2tnR0d1U1pHVlcyNWRKVERnCnVrWmdXK3g5MVE5aCt0bGFhVFVY
            NFBseDNzK2tJTlBESHd5S2RraE9sZWsKLS0tIGl0TUp2MytlbWs0NUVtL1ErOWYy
            MzhSVWpxbURvRGFlcDJnRjFqVWg4dlEKvE+oIIERwrIgqkZU3BRD9mGNBhwz4hf8
            ntbgzuSakM18dKP1EFLfCIMMJQXS4YXk06jmtIr2zr5loD0Q0Wukaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T04:41:05Z"
    mac: ENC[AES256_GCM,data:77AL8DndP/7+/Qov7VFLIOL1b+F6paafk9pLR/8VL12iggsSxCNj1R+hZAWiLtHvEAHjclROBSCVOIsbQH30xncpfYySzqV8/PiOdJUZlioxB6nD4uInmd3ZdjnHEt7x2b1kTqIP4sUAlmkNsowhYkUmmEjyPFah50ti47b0VcQ=,iv:Ahn7vZfzVrSM4BhVd1QYzf5k2x7UbVe4ebRf+3A8QBc=,tag:AVbjidfuZgOEZ3+1KaY2EQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
