apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CRSxQTrt69aH+4SJrLhgseGtwADqYrv3yOopJlo3d7M=,iv:BFM5T567X8WxUIrLE5HQccs2VrstRFBc5KxpEQvCuNc=,tag:Eqmhw8pi6QF/8GlNEIj6eQ==,type:comment]
    #ENC[AES256_GCM,data:MIsFYS+x0h4glGPX65aZ4D+YNaqT5ykc,iv:tGwLzE4snD7meRYvLDjJ8kidIwlitdWequdpEQOsGfg=,tag:UABkL0Jw+HaPHxL6+e92kw==,type:comment]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ASv3HakNWb4+B8wgv23a0D+1ZreqAez+jwB7b3xBjA9LaWuPzZciddMIqolskr3Ry2hpHbYMIXSnqfkX,iv:gfQ/c4QiERcKzSimMqd4Ti8LhtZF8BAzRPhXSdrA2ao=,tag:Oa9S+c/H2Xf/GqOuhBo0+g==,type:str]
    #ENC[AES256_GCM,data:yXY5LU5Le/OkZYqmy9D/K1/5XQv31AoFPQugZGY2rE76jB8dO9on0LVTrXgQ/QInkLjOy0Dln5eN4cA=,iv:n3+MrwpENJBVIE1iE9PmYlUzAMLsjFTNL3zVskbaN5E=,tag:N27YA4DscNMyPv4kmpZ+FA==,type:comment]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:Z2o3AcPP+AWng9al+/fOGn1SAoMd0mQOyGBtfp7JUcKcS17KUaXK0uSo2NN0Gw==,iv:rDgEXS51+DQ0C8y2FXzLfvHv29L8CvNuNKYrFnDkR0U=,tag:AeBet/2MlA5AdCMcscrxcw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:8GSZPw==,iv:bWZEbKMudn16L69OIyDiDN1JSs1U3snAE5w1aXrykRk=,tag:kI0RANcMqM/jrb/7MLMI6A==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:eYdO5TmUZ8dk,iv:53E9sP0VTXrC9S4ygRL0nRHmSZiM+UQVCcPwonQEKcw=,tag:SAjVKJhNWb032X9K+vxyNQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:NhyA,iv:K/KTg1K8Ts5j6zaGpKCEQVde7S+q4Hf1eZ1RK6bLsoQ=,tag:SFbBXc15nfic/aytaaYQEg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:fC3JNlmSCQ628/L3hRLkcGuYPkGDYqHPBFjUmd2AkH7xWZsXLIthtnT40QTVVM+bchwv9wA5FD6PR+9RB45RZw==,iv:VGjFEDwQ+le9OsW1bDSG7zajIH9GW1UiXrPQ9W/6/Ig=,tag:m/KPod7KwbkazCgbDfiGgQ==,type:str]
    #ENC[AES256_GCM,data:Bjgf7nhKUvWqTV7MykdVuKl4A2Vmc3Vq9CNDTDw84/EpqdwaIw==,iv:w+ig+KbzlZiPAX4YwExET8RaAHW9JYbngw+7/IA551k=,tag:cuEDCU8YZzhUTBhhov9E9Q==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:E+ZuGrLDhinyWyjYoGT3UAKnDCMvTIC6Hm4rAiO/Qviss6A9bwJAct6nv8HBhHpQXros6/AaTcKE7a6I,iv:Xp7ffR5saUaQ4QBc6ACCmWYdWd0utvB7GAqa40YONmc=,tag:b1lvjHIJoroaRjgEBXrGtg==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Vis2RmdpYkZqN09ZcDhC
            WWtxYjB4QzUxKzI1M2pRY0JIQzZrU3NYRWtjCjZPb25VNG4zV3lFWjQxYUZkUlVU
            aUo4V3FpdjhiWTc2aXNaQlQyRDR1L3cKLS0tIHVwTFVDYXpqWklCWkJPZ3lvbnJ2
            Yk4rMTZoSGxEdVRXZlA4aUtiTkt4RncKsaGVBw2yn2aP4jZU9IL5chPOeuVylzhW
            W1q3wRxGMZbWqsc6SKJXOYqoe4d7aifI4K+TUWp/4LTf4e8rWTDdhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:25:12Z"
    mac: ENC[AES256_GCM,data:eow6lWbnNb71LqXSaV8g9oTpbr/EEobrUqs1cM+tvqLKA0R36bzLMs1NUGiPJ0sr12NWauqFNRy4DHGYUaw32BdJiHL4EH9ePTlmAHXLzdKqAqzQladd4gEaOvbJu9MpMDSjv6D9fjdPYL8C+evD3XHPnX8rgRkQWk7b7J9qosM=,iv:MCfjfcci00cBQ9h1Fbborr2lu0JmHOFlsqAvvNO8ubA=,tag:ZePhzJ7pf2BNyCwJ/cLBkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
