apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatus

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/pvc.yaml
  - workload/deployment.yaml
  - networking/service.yaml
  - networking/ingress.yaml

generators:
  - secret-generator.yaml
