# Argo Workflows PostgreSQL Credentials Secret
# IMPORTANT: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place k8s/apps/argo-workflows/workflows/config/postgres-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: argo-postgres-credentials
    namespace: argo-workflows
    labels:
        app.kubernetes.io/name: argo-workflows
        app.kubernetes.io/component: secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AW0T,iv:25kgS8mA6cPbNX1BhukKLTbQcFknGzV0ji5jDbCP2iw=,tag:naif38U6RUMyH6OIuutqqg==,type:str]
    password: ENC[AES256_GCM,data:D5hftQVMyZRdHQ==,iv:ogrJDRBLfqdX8HOxuXMkKXrUFkEah+X+xWWfWz7s7go=,tag:Xv6+2QVYo8CX8GOXOGZrgQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2VSRnNNWjJkWWpDU1pM
            bzUvdDhESS9OKzlLdmhwYnJNNEpCTlRyZVh3CkpGS0ZVZHBVdE90UmNzaXUzQWhi
            YVdCUzdIMk5WcWw0bGt0aVpQTHEvR0EKLS0tIHlvZmIrbEZ5UjYvVExZdFA2Y29W
            SWRNRnN1ck4yS1N4angrTFdiS1F4bEUKD5U+DyIrFXM7sZXg46oJg1tDZSX6kqE+
            RlC5Y4ZBTGEaO5BvHZm0URUseSTRVb4cyKN+Zkdfmyc6pc3XDbd6aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:13:06Z"
    mac: ENC[AES256_GCM,data:Tf8ZcLMyEZEpuDAw91DgCfjTEUFH4+BCGgh8kfZfjEGhGGrA12Yp08JTWvatwNp3mUqvoKo298JzAEPrdHf4QcpFjla+QRD1B/2BQt2/FCg9DL06xyY1J6clamr0m5hTeHIM3LZVzgqdpXCWrfXkTgYauTnnSNk2kxapFGXIgjk=,iv:hfHhMgvefftPKWZ+0tcdcsbJHmp+HSb1hOvliPGO2V8=,tag:RF3J2HN+6wgFjRjwmPpnTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
