# Argo Workflows PostgreSQL Credentials Secret
# IMPORTANT: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place k8s/apps/argo-workflows/workflows/config/postgres-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: argo-postgres-credentials
    namespace: argo-workflows
    labels:
        app.kubernetes.io/name: argo-workflows
        app.kubernetes.io/component: secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:M/mEwib/g1g=,iv:qi4B8txzqT5X4JVEL934MU2BX46tNUFdY0mNOitnmeM=,tag:Qqer0/oL4qdp/DErqiVC+A==,type:str]
    password: ENC[AES256_GCM,data:wqa1FZAEL4sHJA==,iv:A66yT+k7e+ZUcKoxPHrPxZw7c7stxBlqPxInuk/G4cg=,tag:gwlW1hZEfKclxQeE9uRFBQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cy81eTVjWFAyZldXWkpC
            QUU0VGg3ZVNtYysvQ0JuZVNmbTRtZjI5ekRVCmM5RkRvUFBGdEM5eHUyeC9WVVRO
            TmhTQjNpeFJuR2x0RGZJSklNeXZub0EKLS0tIG5jMVJydEQ1T25DdXhJVGdHMDcr
            c0R5ck9wU2hqZ2VVMXRRTzJUSUFQencKyOgjczuQijukdRvAycLJeh/2jtWVztP5
            gM0J+A06R4hPl6DpMvbNEVlSjpad0lEg5wIj/kgqKzpcSVK+akGpUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:09:55Z"
    mac: ENC[AES256_GCM,data:H4RMOhC0bHvDegkvFIIP+KteGc952sEcX2c+C9979aX8E+dq7QH6HA32FGdxuo1KqiaEZOG/YzaaXrqvLKyLECuiV+igFb7DUWTsxV9Svl9V7nFhHyJ3jdTVZ4+IxAJAsBpVMA1mtRbE+iUiewZVVEcOlpS5JFh9NgAtzQVbG3Q=,iv:kskuVsdsx/xtAfus6nuA5NXV60KOs5ikgMWuLPssG8A=,tag:NVHw/fDANnFC7jWf2KvS4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
