# Argo Workflows PostgreSQL Credentials Secret
# IMPORTANT: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place k8s/apps/argo-workflows/workflows/config/postgres-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: argo-postgres-credentials
    namespace: argo-workflows
    labels:
        app.kubernetes.io/name: argo-workflows
        app.kubernetes.io/component: secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1OMU,iv:hx+6N+IHuYRszLVLOcxXGpy69XXv2coGWOII3qzmOcg=,tag:EDGza3MRj/z1fcerfvlvOg==,type:str]
    password: ENC[AES256_GCM,data:PIEs+6YSZnb9CuxyI/rKM4BCVqnb8GT5zih9RCS/nGHpYMoTiEtWkq51KeQp6i69B0TrBl2gCaJjA/qy0eSmvA==,iv:EeywBbSr5QZRDMzMjwPdXJSEcRGAZ/sQASFCgY9rmHA=,tag:ocR2pRufJoQ9LsauTeAM0g==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkRrbC9ySEM1eTQ2a2pv
            RWJIWEpjOGxlWXJYYjNxS201Z2NMUS93NDNRCm1yOS8zbmJSQ1crSXNJTWNxcUFX
            QXpFbFdCcVhET3lzdmdUZk9LWnJoWnMKLS0tIE56RW5mOW9rdEZreXlZbjhmMkY1
            NnRPcXFLRTVRQ0xoMGJiSHRzN2dBZG8Kmalpsbn9KJpkOri6D8C/JTR8tYgqgJ4O
            wYw5MjGG/WOxEsu/hxPVHQAPyJs9FxSroiUHGOXrQvCnugV2o6IFPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:18:38Z"
    mac: ENC[AES256_GCM,data:Jxzeq+ydjo+naZGib8Mx1rGeLci4yNUnwO/B1hGUorpZT36Koyh0yk51FQ/o6j3Y6uUs3a7pWOrMqUu4Ac4LtUdhhT+L7rFsMpwy2yPdYcRvJ8rGx4aq38fyY5A5dl/tPjs10MNl9a8L8Pp70HI0olWBZBe7Iy5LkY3dRPAnOaI=,iv:roySSbFfLBsThiY9uAJt6NEBrnoNLkg7YjsBGwIoqGU=,tag:UWyYPmfKJDxsM/K5xiLMLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
