# KSOPS generator for SOPS-encrypted secrets
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: workflow-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - config/postgres-credentials-secret.yaml
