apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - config/secret.yaml
  - workload/deployment.yaml
  - workload/service.yaml
  - networking/ingress.yaml

secretGenerator:
  - name: authentik-env
    behavior: create
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true
