apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-alerts.yaml
  - certificate-alerts.yaml
  - kubernetes-alerts.yaml
  - traefik-alerts.yaml
  - argocd-alerts.yaml
  - argo-workflows-alerts.yaml
  - vaultwarden-alerts.yaml
  - postgres-alerts.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: platform
