apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - namespace.yaml
  - workload/pvc.yaml
  - workload/deployment.yaml
  - networking/service.yaml
  - networking/ingress.yaml

generators:
  - config/secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: vaultwarden
