# This file should be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place k8s/apps/vaultwarden/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:3aw8Mm3WqONInQ==,iv:fREmrjzmNnIGqqk9BNjP8X1ZeFHVVMwgY1A9Hj4Sniw=,tag:XHpkX02m9VpFf8Sz2WyVUg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:v5+UxKNLN9/LNv212JEeVALxhv3VGRF3Y4mRMXUmiZgCOZhTrS5EBD1bJC6vVMso+Lfi4BXiAbwlcJ2xhD5H9Iv4tEfsMIvRx2ExF4vqdeLWLrPc7rWpk7VgkKZewIodhDF7FGjkwtuuo1pq8SDKmF18sjnw7iJRWtVLlOXzhgiuw4tE/BT2qzn94iG/Pc+TKQ==,iv:IUpEm2ALS4mEL12UPoJUH7SLWIkQncphgGdce6Si0h4=,tag:zTMzqsChDtuxLEUOM5FGBw==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL200cW5IaFlPSFJPUDh5
            L0VOS1lqTXlnQi9PVzE3ZHFXVjliZ2xIM2l3CkE5djQvME0rWVR1blBNWlFIQmp0
            YXVnYy81bTBqQTdOOE1ma3ZQVzVEU3cKLS0tIDhyL2YrRk5RZzRnb0lJSzJHSzRB
            a0tncHhncUdoYXl3MXI0bTN0eGdpODAKYrWeOJe2jTWro185H4RhFsQbJWWKbe50
            xr7Y7GbcgZ/n3+EslzMXMnwW6Ett8h/zguCIbH716y6TJioZV+mOuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T18:01:31Z"
    mac: ENC[AES256_GCM,data:2JCVL5jbVgv6Rxns4wJOxx7uz2RCTr6cjqkXS8RJI60rQMaO/qbtGIHWHd0E+jxAOMgNHsncd/zoRXyiyqH0Pnkw3+QgFOIAX2EqmQiSpGW4p5uOC/8IsZ/WWAxhDD1Pnn+tNAbHpNJpIC8/A1CcY6610fqC++yb7iY5NyTqd90=,iv:VkW5qUAy16sy6LwF6V8Yk8kYEN9jEbLB62vLdQDylz8=,tag:FrCCLktgYEot4yOvN36Htw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
