# This file should be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place k8s/apps/vaultwarden/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:3aw8Mm3WqONInQ==,iv:fREmrjzmNnIGqqk9BNjP8X1ZeFHVVMwgY1A9Hj4Sniw=,tag:XHpkX02m9VpFf8Sz2WyVUg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:9cWvfnJ1D8ur45FEHySMOcMRUaC41zouyXvxZ1GWGQSWdh26Z4sgZeGRaHT+o3drbeq8L4g3I0szATPbVefP3JI3/CdQzY5n2YBMINgCtGlwZ2s0wfpXm2K0NpWZbgiu7KnZKPryARAblFpoZf8pX4c3hIKWWRtJm8evVc6UWzDfgdpWzwMvFVJU3gGMx0rsFg==,iv:iF/BtsChwlKH3Z3H7uQDtQiCzddHwwIBErozj+0t60o=,tag:jtfzr9saftjCdQJkx3xunA==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL200cW5IaFlPSFJPUDh5
            L0VOS1lqTXlnQi9PVzE3ZHFXVjliZ2xIM2l3CkE5djQvME0rWVR1blBNWlFIQmp0
            YXVnYy81bTBqQTdOOE1ma3ZQVzVEU3cKLS0tIDhyL2YrRk5RZzRnb0lJSzJHSzRB
            a0tncHhncUdoYXl3MXI0bTN0eGdpODAKYrWeOJe2jTWro185H4RhFsQbJWWKbe50
            xr7Y7GbcgZ/n3+EslzMXMnwW6Ett8h/zguCIbH716y6TJioZV+mOuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:40:05Z"
    mac: ENC[AES256_GCM,data:ExZ31zQjRpsUbCR4XAX2bZWbWvAqfGjXF/Mo8UHSgMx87O8V/pBDeS24IyPZhNQt78s0NtfHdF9cVTOoV8D8lOhArVm8Hg9hIuIuRmAALDhzsyQeFnmsEe5RJ5Olg3REZmP+B6i9YALxA3kwNEU+9IxnFUesRhAQf7epXi0QbRU=,iv:JKCPnyrwyWZ0q2te7vlkDoOnuYFZlEB8QZw6SqOkJW4=,tag:Ug1B5ncPjokSw2RK5hv+ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
