# This file should be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place k8s/apps/gatus/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gatus-db
    namespace: gatus
    labels:
        app.kubernetes.io/name: gatus
        app.kubernetes.io/component: database
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lqYL6qnexkliHP8OqDCF9xQzNv1KMjxMLC/qB2Iiz1d2b4M5L81m,iv:0oLVMCEJwFjsaWGlMVU0HXH82XKLx+appr0R9FL6NTc=,tag:o+o5vU8TFdG5atbPTLSzDw==,type:comment]
    #ENC[AES256_GCM,data:14G73PtQ7a9up/FuFpixL/QlS5OZ+YVo03X/ZSHTU3nLpS1xf9ArBIA1gCUu645adQPTkivPie0mTrKJF7lrM6Wyk24=,iv:2inT24Ye6MkFnJpma00wxmGcjcUOTC12O2wZjTMRBWA=,tag:TKO0ny88SiQX7G1ZXC+UMw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:9kFA2oNX/CzF+2Aa33bAAPv05Q1bU4zkl+Xj6z3/1RMSqax1CBQV9dEMJzrpMq7EAvTpLtvdeTgMUz+vVzxLo5jw/5R1GNktpbNMFBJGwFu2AQbhfewCmCicNg6J3MN6k7eU5jxpiSxjxBUNwQMSB7TzCpZxWQ2WXNqPwNkxbP50ssq7cHC02dEP7EyuRhKT3lmEqr6wLQCH,iv:shEoDOE7shIDYzisYAvnrHo/Vsw4zo62akGSGmW7ooA=,tag:wm1+ud+3feBVkfbEth5r1A==,type:str]
    #ENC[AES256_GCM,data:KJwPV6qVv6N44qG3fiZiZGwWhnstQwc6c0RtOQ3IMg9X,iv:pflHUuL/lXMSMDeQQgCYWuoIeY2kraHAP4S0nuU7NII=,tag:TJIxqpPxJiJpOy3kj/+JMQ==,type:comment]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Ks5xIdSWbbADQoA/SUW8Xp6LtTAjmCdqk2pIFAu70NX7UxbYRt4nW5J+SLe9p0PVZ1bTT84jYnfPyE9UmRb0OED2OvyKRdE1XHqxKf7G8HAQI8WrstInpKauvurVFw9pk6bVEiu9XPIZrV52z6CLLt1fZyr033luPQ==,iv:0yqjB5+8o24DVXliQxMLeheEY9hXuT2/ZibI1F+8pek=,tag:S9OuX1jXNWKd4oZhLCLP6w==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TmJFdHBLM21Ld1B5c1lV
            L2VnV1RPUkpFZmw3QzRpOCtDMkw1Z2xrOGtNClk5Q2xIMVVmRE5SZ2xmbUNXSFBY
            WVg0elA0NFc5eVI0Y2ZVU3ltVTNtKzQKLS0tIDBydWttd0RxOEtYanJDbUcydzY4
            MXlCdXYvbzl6eWNhVVdKbkxzOEJYbEUKItWJB1RoFGVSut0kHLXjLBR6mzSDGjGs
            FLQbbtNMXB5WPALAiF3+xEZoMH+utd9Hjso0ElXTTDC3BO3w2Kjuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T18:01:30Z"
    mac: ENC[AES256_GCM,data:ky216Zzgl8rVZI+B4DXLs7wMK/aRygSgPG1VMb6KSmtur1zs1a7BPfl74FmpfAXH7p9jlXXIO7SRfUyK66Ln7nhbgd2ws1TwSkwnIdBkqhAWp/WWX/MLvzU4Dx7Rfyq7Zw8pIzLXi7fFUTboTGAmpsUBROpO8ndcPdCHoh2azyo=,iv:gexN/mI2diTniQV38uziUMiEPQOO28rzFNmmMOru9wM=,tag:hkSMw0wcfvio/BoL90tSgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
