# This file should be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place k8s/apps/mqtt/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: mqtt
type: Opaque
stringData:
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:YYFs8Rk0vC4nnA==,iv:+DsqPbDWVmuPzSdsvuqld/mvVf26HKgNLwAmh2icmhg=,tag:UhD+IaUM9+TWSD8csz57aQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbnZ1ZlhwWEI3aEM5UDBu
            T203ODFFN2ZXQ2lMR2YybXNXN3FIOGtHMlVNCnFzSitzb3lHR256YW1yUmVTY09h
            K2hkUEdOM3IrNkI3a0g1R2FMcm5VVWMKLS0tIFF1SGkzRFZIMkZWUS8rSUk1dEY0
            UXlmVW85bVliWFcxVHBPeFJEVWlHdTAKcrdJEFBwedO4t/ioOManFBYu7Us0Bl9o
            b9Hs8QGriX2tzrXxK31vuUSNTnHyx7xUUrtBIqVU3OV5BcBE82Tq7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T15:45:12Z"
    mac: ENC[AES256_GCM,data:QMmeA+A4AUFki5rC9o+8kXCFWD81hXc9KF5xf+dNfdwuv75ooBgiwOWHd9PaEYBZIIGH200eJ1ewknhbmR6XJhCajirCXolBJ6J9ED8gBM/NwdIBv1bJtgZtIsRoD/Eu7p8bS6BriSmnoutvoqHsxd4mt+OKSZ7w2jxVzbPAS8E=,iv:/aaQT5B3zEqvWvpq/tnTn564Te545NRBsC2Uaqiqge8=,tag:RMeW21Djr8TZGKaK4cg1yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
