# KSOPS generator for SOPS-encrypted secrets
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mqtt-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - config/users-secret.yaml
