# This file should be encrypted with SOPS before committing
#   sops --encrypt --in-place k8s/apps/mqtt/config/users-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
    namespace: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZM7iYYkzgbB09oSfw/nzMRlH26BFIVDDps86bLh7j9OsJGKl5Y7j525xCk/dujDCQYDrFDxN0Q==,iv:dTBkGAxeAbeEdRrMPQlzxCEVR/ngFbX+WhVPR/yD24c=,tag:ND7dnZuOIpEVP545h0F87A==,type:comment]
    HASS_PASSWORD: ENC[AES256_GCM,data:Am9WdI9UDI9tYQ==,iv:HnRx/XL8UeIVPifCZ/0lsQUvgdbHHdL6vi0VcSdxY+8=,tag:XaLWOCRHFLL6IriIBVDRZg==,type:str]
    GOVEE_PASSWORD: ENC[AES256_GCM,data:zZT/YE2B50m1WQ==,iv:M6EWRr4lvH2GcZFOOEPjm4QWU4yg56BFnr8qPzLhZn8=,tag:0PJwkxlauvwIeGgSooTl1A==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RFpjOFNwUnVscE9ibTZL
            SGZqYm1sYTVlSlFRWDJ4Zld6KzZxOE93R2pJCklUUnorUkxyWDI1VGswQkJuV2Er
            NVBaNG1kbVZtTzZqeGNneDdVMVlpdzQKLS0tIHZDcVJqNHphQW5pVk1zWTFUQ1F1
            a1RFa1BZYUswNC9UbytWT29GK2Q0WEEKNCabSDmG8cjpsDWUKRKXMqPfW3TELbMH
            3kKLasFoHiomYPaGe5aBFHUR+P8kKjOXmq1kcGmijl3nwD/q5gVDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T02:51:42Z"
    mac: ENC[AES256_GCM,data:FlRmm7lO9UHlVe6qBL2GYupobkycPp+cxplXGwcWF01PXazaT791AfVB5vAJZoabLf1l2evtdwRgp73ksKt6QgWKr97QIiCt//jVPGPRNHcQpPzXQ7KIHJrBloMiX7pJ1Seyd74X0SLRoXu1A6btxKV8KngZO0e9T7juyuijb4Q=,iv:s4PRUGegpix3sohW/+lkWCW2c70a+NydVCNWvrExB0M=,tag:vRfeVzeT4Qq3qkaQFdQBEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
