# MQTT client users - Encrypt with SOPS before committing
# Run: sops --encrypt --in-place k8s/apps/mqtt/config/users-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emqx-users
    namespace: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9gTw4EAKLV95olQu4YlNg0jm8Pc6Z3VBRXUFYxzdpTANmQM7kEKx2+hI9IJpNAPC7GT/zJIhosM=,iv:HIV0oFZpl2PSEYlgaqLVoBdhd/XcjqrKsFYNncpTm7U=,tag:QeVtEWPgQbQTqNP/EdAXUg==,type:comment]
    #ENC[AES256_GCM,data:HOx3iQsxcE6S3G+AgO5nRY+FUcdEWMjFLaJX1jzc3w==,iv:1M4HRaoxtgGWdTvfCZrY5eLmlxihWCcjFLQB3M5JTfs=,tag:KP7u0RB+LZ9xOMAWpAqDeQ==,type:comment]
    #ENC[AES256_GCM,data:9Tjf90xUBIB5oZfYDdQwoJSVKlsFVNYQ3KxnHQ0qVYDLagwWv+aCU8o4aHjtXjDNhbcpiqzcBGn7oNT+Ruo=,iv:o7CfVLquPXqIxH+QnfGxc1Cxl4TVi/Tabi3QGtg8AT4=,tag:W2ZKdfImbURp8to/YSz3Ag==,type:comment]
    HASS_PASSWORD: ENC[AES256_GCM,data:cQf1xDWwQls1Hg==,iv:+2W0EHc5iF0Wl0iIW5oIV5ozLDfM4GKTvsHpUV5+Vm0=,tag:9lYqnOpKJ6Uq9Ch/VErebA==,type:str]
    GOVEE_PASSWORD: ENC[AES256_GCM,data:N6Hw4LTs+XAkFQ==,iv:XDMbg5FyoMFWuyIR6YBZZTV8jTx0JKasf1mEEAv4oWk=,tag:KAVZCSDDCjqSr51ofSI1pQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM2EwSVJQemowQkZlVndj
            MElGRTRQdXNBTFVNay9GbDV5V2Zhdm5YMHdFCml1L3V2cXRPaXVkTGlOK2szODY1
            V095ZW5HZ2YvNmNsWnlPS0UyK3BKVlkKLS0tIDhFNTZmVjBvdGVBRU9IK1BzZkdE
            MEd5ZEZPNkxqUlBmakV5c1QyUXQyQmcKirfl7thxCHwpmIoWqw0wzS7hXU8AZ8UB
            Imdh1U8p7/VW8txRubS7eedMK7W4C81PwDsNnfLqkvByrUL8jVbbvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T14:10:16Z"
    mac: ENC[AES256_GCM,data:nPtPnw8kPUgd8V0U2NnWV2FIpQgmxehJJy0g40AfQytyhwE0OzHrE2o2dRsiftWIAYCtXFqzwwdmnYSkxDpu+byPGNH+Vo7c8kBxRJufJjpMxETgsFy21VIfV90mlKEN0UdEKHzxTWTY5OXirkjRs+NIgCq1DjyihoMwP3KAj60=,iv:CmLVTwZxaPAffkLmLkHA9tptlbCu+zY6H2XgW1StWmM=,tag:+yf6GVLe9ZVtd5uxce4g4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
