# pgAdmin Secrets
# IMPORTANT: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place k8s/apps/pgadmin/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
    labels:
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/component: database-ui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5B++x5A1EKqoN/n6j5bDWbYrLL9waBiiT3RHot1wGxG6TSY+WX0=,iv:jSxjCW0wD0jqWUFofaMYwK1vTD9XPEPGZ/4Znch5+HA=,tag:ZqKoogNyr0PM+HiiMWCXkQ==,type:comment]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:X0rfrfMflSJGuB/VndFg,iv:1jblckq7OZfHhr8/WRKRzackLsdXJXlRDmThVCc0gIw=,tag:kTd+S5KOuNAFx7HX0WZ3ig==,type:str]
    #ENC[AES256_GCM,data:4L9oROX4MgDAn6JlBZynPczlnZlZZQ1y1RXecpfiIw==,iv:QlenRnm3BmYahqEEmDCJ6S6xTqU0HhVz00M6n8zWULQ=,tag:9T/Rc82F9Qk37AkR9vYPBQ==,type:comment]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:psBaxtcbmsJteQ==,iv:XNWl5Bq7U1N0icckigSKfgesY08S8m6TYFpv7WtQdhQ=,tag:Hm628z091umsFXj6XVkOzQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZTRzam1QV3o4UGZlT2E4
            akFkSWc3RjBYZ3JqQnVHaGVycWZhMHY0MjNnCkoxcjFvdEl2SmNBS0hmai9EQmRC
            RnFIc0g3bHlFRGFGekp4SHgwbGZWTW8KLS0tIFJRQnVsV2ZOa3AzZXF4b2FQc1E1
            TmlvTGxUdkJWb0pYMndYRHY1ZU51ZGMKXguXXMC4tf/qG0dbDA/jDRyUy1XBSKp7
            PfXSbWqcseFhwW89fYGlDw4qvViXV9g4gSC5OY+UjMI30nJM1mmw0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:56:13Z"
    mac: ENC[AES256_GCM,data:Sn/eBC92mtnRR++wIZz0DyvugR9hdnHWorXuHCoP6gA4MmxVVVrDL8NWN8sZYUMGkvOU7hQHq71QVcqGEui4whk3AWOqs1LWMmLitRL8Nw74AXaNHXReH4andHZCld+V0bSOUjG8IteUpqz8FF9ldwDmNUY66rt/YDKF5AUDzaU=,iv:Rsmt3gcyj9q/2vusxmAGE8c/nz7j2NxbWv7/fwZwomY=,tag:3wM5vTqyBhI2/QtmBkV6Dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
