apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: APP_NAME

resources:
  - namespace.yaml
  - config/configmap.yaml
  - workload/deployment.yaml
  - networking/service.yaml
  - networking/ingress.yaml

# Uncomment to use KSOPS for encrypted secrets
# generators:
#   - secret-generator.yaml
