# KSOPS Secret Generator
# This file tells kustomize to use KSOPS to decrypt secrets
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: APP_NAME-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./config/secret.yaml
