apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle
  namespace: dozzle
  labels:
    app.kubernetes.io/name: dozzle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle-pod-viewer
  labels:
    app.kubernetes.io/name: dozzle
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle-pod-viewer
  labels:
    app.kubernetes.io/name: dozzle
subjects:
  - kind: ServiceAccount
    name: dozzle
    namespace: dozzle
roleRef:
  kind: ClusterRole
  name: dozzle-pod-viewer
  apiGroup: rbac.authorization.k8s.io
