apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cronjobs

resources:
  - namespace.yaml
  - config/rbac.yaml
  - workload/cleanup-completed-jobs.yaml
  - workload/cleanup-evicted-pods.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
