apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-dashboard-ingress
  namespace: mqtt
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/component: dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mqtt.int.jigga.xyz
      secretName: emqx-dashboard-tls
  rules:
    - host: mqtt.int.jigga.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emqx
                port:
                  number: 18083
