apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
  - namespace.yaml
  - workload/serviceaccount.yaml
  - workload/rbac.yaml
  - workload/deployment.yaml
  - networking/service.yaml
  - networking/ingress.yaml
