apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alerts
  - servicemonitors

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: platform
