apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - namespace.yaml
  - config/configmap.yaml
  - workload/rbac.yaml
  - workload/deployment.yaml
  - networking/service.yaml
  - networking/ingress.yaml
