apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - workload/
  - networking/

generators:
  - secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: unpoller
      app.kubernetes.io/part-of: monitoring
