# KSOPS secret generator for UnPoller credentials
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: unpoller-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - config/secret.yaml
