# Open WebUI secrets - encrypted with SOPS
# IMPORTANT: Before committing, encrypt this file with:
#   sops -e -i config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secret
    namespace: openwebui
    labels:
        app.kubernetes.io/name: openwebui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4eyUs9HBHQT/ipucbxvHVRuCP+iGdyh0lblHqh9onZ1v1Jh08Wr42Qy26QpQhCZPy7YvfzXnjNSFVLAfh0X+QIN9i5fLdKdxZf6zE44TUCWr,iv:WmrmZmerNP+6d5b2wIcz8U8ZS0hNPjUMlyFkVWO1PmA=,tag:UFDEhlL+c/zWW72cChPlhQ==,type:comment]
    #ENC[AES256_GCM,data:Viby+kcwOAPUpM25kirk7EnoSeRo1soe6qppHgXtjhtZ7W9E,iv:pxdCOcwgmCoyoN3KoLiMuFydxXWCFTQrRMG2xtpk+ZA=,tag:V515FJ5Ek9mlCtrXzdQp5w==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:rLuEWqkg2t6bFYa6c/U2MIqAR2J2V86iIupthSlJoQjCPwwXvTj+iIpt1vw43yOYGaxr6qK5dast3Ik9O5Zl4Q==,iv:mRGTOfjLM0BapsTjFEct74s4f6H8GxDR4+3I3diKOsk=,tag:4Fxz7HZJRvPxHJozoTffjw==,type:str]
    #ENC[AES256_GCM,data:heEs3goa8pIsrbAjJSkrgriloU7WsK6RWD/VvBv2unGXn1Kf4ftn7E9Kai2NVBk84pXW9A==,iv:+J5VXGKOBJPHS6BcWAbhKPFnwUvllYaeIIwz0Oh+NfA=,tag:e5yKK596dRYRdJrFKj7cmA==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:JwskYR/ro4h4VtwSEctbp2pVm8QGwdyFeGhO+cccI2BwJQbIZu+tqH7l6oCG0t82wrEcxy0Br2qTyI/dNTOlofokO644ligshi+r8HJgWWp6g8m9qYPuaUHwjwWqDkjoc59Unom1pUi52lcXjRCU0kdKnS1XNX4sDiHB4GZuiQW0nYGebN+KdhScIIaJecnwxLoutxVjqGtcJnfB6zj1aTk9X8E=,iv:HKaW7JStYx6TlKfqs8dazOKG/AtYqHndSy21LtuBoSU=,tag:w94lnpQVt2GZdbsQNQGQvg==,type:str]
    #ENC[AES256_GCM,data:+i6GdA5SeYsNawIGBqZRVsVx7GDoa+6qiTePyWTpxMysUjH5Ve/Du0DOMoKaDmSfsV+AC5NIuzFWeOlMR8WgOOhMEF5NJJS64kE1t0SOpw==,iv:r2zxOBu2M0XzwDiewZjNURnO2JSEB5hBk1fR7UKvd/I=,tag:RMwcYTFvfk4+1M+hmScGwg==,type:comment]
    OPENAI_API_BASE_URL: ENC[AES256_GCM,data:cbvKQS3W34mV1ja/6L6KAoaB3tPXBLpofg==,iv:xYYLx2AFCSA9TWzH58a5K/Tgesp9yK0OqnpdfLlIysI=,tag:tvlL3jlr4mwDipNXZoxhNA==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WEZnN3dtSS8vcHFEczBT
            WVRBY0FUUElwZ1BHNTlDTUp6UU9zN042Y0JFCnc5UXZwK0prUjUwN28yV09HRDdm
            L2JRQ2lCdDRTK2tPaC9kTkVDUjdCa0UKLS0tIDRVVkNOeWxSSkdwY01tdE0vTmZn
            R210NS9vTHk5ODN1bytsRlB5d0hvVm8KWY86eCVsh6vpgXmuQZAodHs+92HdrtcZ
            LN40NqqNGYVRHJfs5uEBe6oq4qp3sSTLNoY0nC+z0vgWsketlUgv8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T22:58:17Z"
    mac: ENC[AES256_GCM,data:eiAf+ODLslnRSzDVb6kvBiTY8DOAkOPxQM+Sf/TCh7mp5mqNGpQEKTY7j3zV/rZTXS2S96NgglmdIAes5QoK9rh4fTMvvHztR0XDP6f0M8fTUDKmId7k2vArKql6990bzDLriGFVk4G+qFbPd1I3i+bT0IWVjeuaX49Xkk25KFg=,iv:oBv/uw/nx/O/avkdtbroTIwFkqegoZtB97PvLOFEd/g=,tag:In2Y8nOhyEkzIVjKxYFwyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
