---
# ServiceMonitor for Cloudflared tunnel
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloudflared
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudflare
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
