apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-workflows.yaml
  - argocd.yaml
  - ceph-csi.yaml
  - cert-manager.yaml
  - cloudflared.yaml
  - postgres.yaml
  - unpoller.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: monitoring
