apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgadmin

resources:
  - namespace.yaml
  - config/configmap.yaml
  - workload/deployment.yaml
  - networking/services.yaml
  - networking/ingress.yaml

generators:
  - secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: pgadmin
      app.kubernetes.io/component: database-ui
      app.kubernetes.io/managed-by: kustomize
