# Dozzle (Kubernetes Logs UI) Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dozzle
  namespace: argocd
  labels:
    app.kubernetes.io/name: dozzle
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: observability
    tier: app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:eosho/jigga.xyz.git
    targetRevision: main
    path: k8s/apps/dozzle
  destination:
    server: https://kubernetes.default.svc
    namespace: dozzle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
