# Homepage Dashboard Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: dashboard
    tier: app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:eosho/jigga.xyz.git
    targetRevision: main
    path: k8s/apps/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
