# UnPoller - UniFi Prometheus Exporter
# https://unpoller.com/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpoller
  namespace: argocd
  labels:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: monitoring
    tier: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:eosho/jigga.xyz.git
    targetRevision: main
    path: k8s/apps/unpoller
  destination:
    server: https://kubernetes.default.svc
    namespace: unpoller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
