apiVersion: v1
kind: Secret
metadata:
    name: postgres-minio
    namespace: postgres
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:DuFmtAe+bkA=,iv:WqZX5000dGG3OJMRvNKjYLlmznr5ry4rAuF3zu/h3hs=,tag:tflCD+a/Cv11QXCWnQLMyg==,type:str]
    secretKey: ENC[AES256_GCM,data:E1ni/LJ/Am8=,iv:ZH70tnF2ytK7t//SYXam+K6jMB7YRz5rVBWzm8M7lIk=,tag:wtO0YMzTbbXHcOQ7tE2FxQ==,type:str]
    region: ENC[AES256_GCM,data:eX5/NbaJnHrW,iv:Xn98xYntpG5Xn1CLNAXCapZbKXUQlF7GML2YipLCoT4=,tag:xMvPlocZR46hzk7It6fLpQ==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNnlGWjN0WEpJc3NoN2lM
            Nnk4YUNTYndNYktCbTI5WEt4YStUWURSM1Y0CnIzSmdXV2VNYStPOUxlT242TEl0
            S2NwQ3FIdW9RNk5NWndFK3ZEZ0NCaUEKLS0tIGhMNDZQRkczMnhTZVQvYytReXRv
            WVpWalhRaDBVN21EMFlmZXJNMEtyTzgKl8fGccBXQ8c/vTmfEzBj65GIMRGskjIv
            c/W/lwHk9T5MpAo/YicwfpDIi1QXvP/V7oxdVSxvM/NpLYtLYPR+DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T05:20:34Z"
    mac: ENC[AES256_GCM,data:bolOfAMde+/kxxsY2Gn2eNmFiJLrH6w1F6dlWXxaMT8n3DYuz9eE2yxtcPM+JRB0FPDlgUQ901cu3M/Y1sf+4Q6JwquDKY/+DEK0mLddXPmGrZkOhxd8K+yBPP/v4caFsETfLBoLaqDPo3/E7r0rPHAUEzDQAU8irs4E+ArnpKk=,iv:rtqaCM6wTySWiV2UxTy1BBll2SUDtPss22tPsHbIfVg=,tag:gqKacBRy1YS3CBDmXIV7gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
