apiVersion: v1
kind: Secret
metadata:
    name: postgres-minio
    namespace: postgres
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:vMdHbE9LZdy1+SE=,iv:N6Jvl553Hph0otQmT676QdL7lx56WUvT0XWexiE5SCk=,tag:8Q7ao6aH/hjbxZ5PkGJ5zg==,type:str]
    secretKey: ENC[AES256_GCM,data:I1eWcKhzSId8gQ==,iv:Pw2KGsucHBTRSNMm52Zvvj6bIRnTIp8Ufdalnq0j+60=,tag:E4GiCJagMtDzSmhbD/Rkvg==,type:str]
    region: ENC[AES256_GCM,data:tDL5Nwep0tCV,iv:/IJ0MtcDUj+SOOQAKPIEEx2T5GdM9V4yeV4IEisIT30=,tag:D/1colkCShaW59QKf4h2gg==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaUlYY2pSUUIyMCtKL3dp
            MnZEVDJVcTUyRFd6TXJhTnlsR25KWnNDbkhvCmgxK3RzR2szMlAxK01KZ3ZGdVk0
            b2VWZFlNVG02dEVpSDBxOVlvSllyTVUKLS0tIEt6WE02YWxBbTVGUEFDcERnaXZX
            dVJlbnFGb2M5Vm1EUlhwTzZjcDhVV1EKn/EjVjUP0bO4ligc0zNSFOE9PMl/bgWS
            T7R96ZM3Czi0XuvMoSkeDwmOgSNBTGEFuWKH0nCIqoPlX3YAyhOCUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T05:33:24Z"
    mac: ENC[AES256_GCM,data:udqslumJ36wxe3AJETtV53vG6mCJmte8LwzEL86CAC4nrFZcfb2hKdAAEfVHdv17d1PM34zaqH47deVGI5dz6CC7apAjWcm4Px8zAepioJsheER9PM8itfSJ2vafTztQS8Pydfh0ALMyeXq1fr5+3zAW+gyBdwElJJjaWQ/F69Y=,iv:OQE9JPiiGsO+aWItdWMo/RfAEeJuONHQX0xTE2sUt/Y=,tag:Y6h6yY60gnT+6+VU9ELRQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
