apiVersion: v1
kind: Secret
metadata:
    name: postgres-minio
    namespace: postgres
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:Oi64iVZYLRaF+wE+rKOcjdy+bUk=,iv:m8+HDu7KPHbVxiyL8YXRrFf5pAPvzDJoBBbHabfpzAg=,tag:BTVxigbp0s314WZ3kgOkNQ==,type:str]
    secretKey: ENC[AES256_GCM,data:IXUHEBM/4di9zHQjYNOzePuRh1X5wbySWlaj5xKDFQydJeEPfxaByg==,iv:keJGraiqUyOe+MkAC4a4Oj/aRct7euS/GJp50RhZPZg=,tag:LxNvxnArgUcYPJd1VYDD6g==,type:str]
    region: ENC[AES256_GCM,data:wrLl8vm3cVmr,iv:oCCbNV9iz7DLTSuOybdjzqTSlIGcQa9Kik20/CEkCJ8=,tag:ouwDsOedLvf+Q86S6NhnNA==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM3dGdGExM1R6ZS9vdjZW
            T29jeEVlZWF6RGxmNzRzaWo5ZllpZ0pIRmdFCktRMEdpL0d5d250L1pnV3RWaE0x
            UThUelpmSm81aThpNDFwMEtpaUZlSEkKLS0tIG8zb0JWWkU2cVFrTUMrNXd2UldS
            dExWd0tFSWZwZUdHTzUxS0ViQk9IeDgKfgeF/yxaKpnkM7+fngulfZzoMsr+kyNS
            RHW07FkHYq8Le5e9UQNxkhOojQ5UJU5gIEGjjV0D5F7OIh94VSKCvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T05:46:15Z"
    mac: ENC[AES256_GCM,data:b/FMEREq2Dio3EuRcB2alWJ01D4j1YW2Cd+1pCEDuDzxwatO6WeoPo+S/pdtNevuNqvc2iN23erZOv+/bEjPf9yY5PjBorVT96MxXnZ94Cw/EgmRL3a6e4MucUrtj/6APnqCAjbQVObDuWJMmvzvseHSaRAAl8fspmhqom1mBdA=,iv:ox2BQRMRtd0pHv4YJ3Gigz/hJLU/cWhAO2dwkNvitt8=,tag:BZhFTPYGcZdoCb1T9opZTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
