# PostgreSQL Secrets
# IMPORTANT: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place k8s/apps/postgres/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: postgres
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:5dSUPQcYops=,iv:4iFOF4c8vnaGkwODbYQeyPtqQYPpAume4+ar9lMBGAE=,tag:PJOHb4q9iaCLxvBSZ8YLdw==,type:str]
    password: ENC[AES256_GCM,data:xyHW94GtC8Q4iA==,iv:EHzJnrBOvhyLdZWKkt0LFkcOWo27rAGGAQbIlKYi/Pg=,tag:8oEDdWYQaFJ2q0zh6IJcHg==,type:str]
sops:
    age:
        - recipient: age1n54ssq34zj4z6wdghnr7pq2e8xv7t9ag3j37cefsq4tvvq069sasnpmdq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueGR2WjJNWkcvRnF6UWJm
            NG5YR3gzQlM3bUxaK0Q0OCsyQldUZ2R2YVhRCjVWWEtxZFNOT0xYR0xOV29oWndo
            ZjdUVWM1UzU0bWVIMVpRQlFVSVZzRkUKLS0tIGRWSXpkdVdMUWFjZXVreWN4U2pT
            dStjVTNDM2ZFa05HbHZYNi9CQk5NaTgK89cdWzBAEq8GrWh2/nDy0prOYcM3h/+c
            wRjCUDL/Q7pjun5YRw5lznOEs2W712nZvYZm3z/vz1VRFkOAniuRzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:40:21Z"
    mac: ENC[AES256_GCM,data:1IIAcE+dE8JVmvhFhNssDlFe45WxO40p0h4vkoptPz/etk4OYV1q9D/KJpHlSkj2uwXtwZXELMfikJzIxvkDlgJmxeGBrE3Qj8PVMvz1zCwQCGyhw3uGo4nAXmjKknhXzPLE0w9Uo+x4RQIqIchd4nuALZWtyCRiI5QgQzluCvg=,iv:LyX8r81QzlbMrDzZxn0APH43k1N+4eut22X8SDkh5nI=,tag:xFZ2zuugaqjL3CuI7CQLbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
